apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress-service
  labels:
    app: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: prometheus.example.com # here we put hte subdomain we want to use to reach prometheus
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090